services:
  web:
    build: .
    container_name: stripe-test-container

    env_file:
      - .env

    environment:
      SQLITE_PATH: /app/data/db.sqlite3

    ports:
      - "8000:8000"

    volumes:
      - ./db.sqlite3:/app/db.sqlite3