# Generated by Django 6.0.8 on 2026-08-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',), 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
    ]
