# Generated by Django 6.0.8 on 2026-08-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
