# Generated by Django 6.0.8 on 2026-08-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_discount_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
