# Generated by Django 6.0.8 on 2026-08-05 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_tax_order_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Налоги', 'verbose_name_plural': 'Налог'},
        ),
    ]
