# Generated by Django 6.0.8 on 2026-08-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_tax_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='inclusive',
            field=models.BooleanField(default=False),
        ),
    ]
